# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo_tutoial' do
  # Comment the next line if you don't want to use dynamic frameworks

  #사진 라이브러리
  pod 'YPImagePicker'

  use_frameworks!

  # Pods for Photo_tutoial

end
