# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unsplash_with_storyboard_tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'

# Pods for Unsplash_with_storyboard_tutorial

end
